### ISSUE TITLE
Redirecting to new page

### ISSUE THREAD

**Issue by Aanandgupta** [deepanshu1422/List-Of-Open-Source-Internships-Programs#67] opened 2021-02-08 18:06 UTC
Whenever someone clicks on a timeline he must have to be redirected to a new page for providing the better user experience

**Comment by vybhav72954** [comment] 2021-02-08 19:07
@Aanandgupta Great Idea, and definitely I agree.
The problem is, am not sure whether it's possible with MArkdown or not.

By Markdown I mean, Native Markdown, without using Inline HTML, can you confirm me if you are aware of that. In case it's possible with Markdown, I would gladly implement that, or you can do that as well. If inline HTML is our only option, I can't comment as of now if it's possible or not.

@deepanshu1422 Shall we implement inline HTML in the Repo?

**Comment by Aanandgupta** [comment] 2021-02-10 17:51
Hey assign this to me i will give this a try

**Comment by deepanshu1422** [comment] 2021-02-10 19:10
> @Aanandgupta Great Idea, and definitely I agree.
> The problem is, am not sure whether it's possible with MArkdown or not.
> 
> By Markdown I mean, Native Markdown, without using Inline HTML, can you confirm me if you are aware of that. In case it's possible with Markdown, I would gladly implement that, or you can do that as well. If inline HTML is our only option, I can't comment as of now if it's possible or not.
> 
> @deepanshu1422 Shall we implement inline HTML in the Repo?

Yeah, for sure go ahead !

**Comment by Aanandgupta** [comment] 2021-02-15 18:08
I explored a lot about it on various platform and discovered that this option is not available with inline markup due to some security reasons

**Comment by vybhav72954** [comment] 2021-02-25 07:16
@Aanandgupta Thanks a lot, I will close the issue as of now, though I will keep this in mind and will see what are the possibilities.

**Closed by vybhav72954** 2021-02-25 07:17 UTC
Labels: enhancement, feature, good first issue, help wanted
